[profile.default]
  libs = ["lib"]
  out = "out"
  solc = "0.8.26"
  src = "src"
  test = "test"

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

  ast = true
  build_info = true
  extra_output = ["storageLayout"]
  ffi = true

[rpc_endpoints]
  base = "${BASE_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  sepolia-base = "https://sepolia.base.org/"
  sepolia-unichain = "https://sepolia.unichain.org/"
  unichain = "${UNICHAIN_RPC_URL}"
